{% set name = "dejaq" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dejaq-{{ version }}.tar.gz
  sha256: 1e1b6148bb420ce54528be233cfc1892ce0309edc2f8a0e48d863aed8783458c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - tqdm
    - posix_ipc  # [unix]
    - pywin32    # [win]

test:
  imports:
    - dejaq
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - numpy
    - tqdm
    - pip
    - posix_ipc  # [unix]
    - pywin32    # [win]

about:
  home: https://github.com/danionella/dejaq
  summary: Déjà Queue – A fast multiprocessing queue for Python
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - bjudkewitz
